### ISSUE TITLE
How can I build the S10 kernel

### ISSUE THREAD

**Issue by abosaad11** [awakened1712/android_kernel_oneplus_sm8350_build#2]
Hey awakened1712

I couldn't find a way to contact you so I thought I could ask here.

How should I build this Samsung S10 kernel?

https://github.com/awakened1712/android_kernel_samsung_exynos9820

The Kernelsu website refers to your repository but I can't find build instructions for non GKI kernel. I appreciate any help. Thank you.

**Comment by abosaad11** [comment]
Hey @awakened1712  I appreciate it if you take a look at this. Thank you.

**Comment by awakened1712** [comment]
> Hey @awakened1712 I appreciate it if you take a look at this. Thank you.

 Change your device accordingly
```
bash build.sh none beyond1lte
```

**Comment by abosaad11** [comment]
> > Hey @awakened1712 I appreciate it if you take a look at this. Thank you.
> 
> Change your device accordingly
> 
> ```
> bash build.sh none beyond1lte
> ```

Thank you.

I get an error:

https://github.com/abosaad11/9820-kernelsu/actions/runs/7128385440/job/19410247289#logs

It appears to be missing this:

```
make[1]: aarch64-elf-gcc: No such file or directory
```

I tried installing the toolchain:

```
apt install gcc-aarch64-linux-gnu
```

But that didn't work. What's the proper way to make this toolchain available for the build?

Thank you

**Comment by awakened1712** [comment]
You can follow my github actions of another kernel https://github.com/awakened1712/android_kernel_oneplus_sm8350_build/blob/build/.github/workflows/build-ksu.yml

```
    - name: Checkout gcc toolchain
      uses: actions/checkout@v3
      with:
        repository: mvaisakh/gcc-arm64
        ref: 05cb20a52f12389c3f2340b5103485108feae302
        path: toolchain
```

In build.sh of 9820, change prefix and in build.yml change PATH accordingly
```
    - name: Android kernel build
      run: |
        sudo apt install libdebuginfod-dev
        export PATH="$(pwd)/toolchain/bin:${PATH}"
        cd sm8350
        bash build.sh
        git log --no-decorate --oneline -n 100 > out/ak3/ChangeLog.txt
```

**Comment by awakened1712** [comment]
I made https://github.com/awakened1712/android_kernel_samsung_exynos9820_build, you can fork and adapt for your device

**Comment by abosaad11** [comment]
> I made https://github.com/awakened1712/android_kernel_samsung_exynos9820_build, you can fork and adapt for your device

Thank you so much. It's building now!

I have a question,  why are you using this? Is it important?

```
    - name: Checkout patches
      uses: actions/checkout@v3
      with:
        ref: build
        path: patches
```

In my repo, all it does is copy the lineage-20 branch which I named into another branch `build`, and in your `android_kernel_samsung_exynos9820_build`  fork it's empty. And yet the build works in both cases.
